name: tacha-symfony-dev
services:
  www:
    volumes:
      - ./:/var/www
      # - /var/www/vendor
      # - var-data:/var/www/var # Ignore var/
      # - /var/www/var/cache # Ignore cache
      # - ./var/log:/var/www/var/log # Check si le fait de prendre log ne fait pas trop ramer
    build:
      args:
        HOST_NAME: "localhost"
        LOG_LEVEL: "notice"

  mailer:
    image: axllent/mailpit
    ports:
      - "1025"
      - "8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

volumes:
  var-data: # In future, for monitoring
