version: "0.0"
services:
  mysql:
    image: mysql:${MYSQL_VERSION}
    container_name: db-${APP_ENV}
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "root", "--password=${DATABASE_ROOT_PASSWORD}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - db-data:/var/lib/mysql
    # restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    ports:
      - 8080:80
    depends_on:
      - mysql

  www:
    build:
      context: .
      args:
        PHP_VERSION: ${PHP_VERSION}
        APP_ENV: ${APP_ENV}
    ports:
      - 8000:80
    volumes:
      - ./vhosts:/etc/apache2/sites-enabled
    depends_on:
      - mysql
    # restart: always Relou pour les tests

volumes:
  db-data:
