name: tacha-symfony-dev
services:
  mysql:
    ports:
      - 3306:3306
  mailer:
    image: axllent/mailpit
    ports:
      - "1025"
      - "8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

volumes:
  var-data: # In future, for monitoring
