name: tacha-symfony-dev
services:
  www:
    volumes:
      - ./:/var/www
    build:
      args:
        HOST_NAME: "localhost"
        LOG_LEVEL: "notice"

  mailer:
    image: axllent/mailpit
    ports:
      - "1025"
      - "8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
