version: "0.0"
name: tacha-symfony
services:
  db:
    image: mysql
    container_name: tacha-symfony-db
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  # phpmyadmin container
  phpmyadmin:
    image: phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      PMA_HOST: db

  # Symfony apache project container
  www:
    build:
      context: ./../docker/php
      args:
        PHP_VERSION: ${PHP_VERSION}
    ports:
      - "8741:80"
    volumes:
      - ./../docker/php/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www
    restart: always

volumes:
  db-data:
